### ISSUE TITLE
Crash with `wxToolBar::FindToolForPosition() not implemented`

### ISSUE THREAD

**Issue by neongreen** [suurjaak/Skyperious#26]
Skyperious crashes when run from source on Arch Linux (wx 3.0.1, wxPython 3.0.0). It runs fine if the `if isinstance(ctrl, wx.ToolBar):` code path in `wx_accel.py` is commented out.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "src/main.py", line 14, in <module>
    """
  File "src/main.py", line 518, in run
    run_gui(arguments.FILE)
  File "src/main.py", line 436, in run_gui
    window = sys.modules["main"].window = skyperious.MainWindow()
  File "src/skyperious.py", line 236, in __init__
    self.Show(True)
  File "src/wx_accel.py", line 71, in Show
    self.UpdateAccelerators()
  File "src/wx_accel.py", line 85, in UpdateAccelerators
    self.__shortcuts = accelerate(self, self.__use_heuristics)
  File "src/wx_accel.py", line 345, in accelerate
    shortcuts = collect_shortcuts(window, use_heuristics)
  File "src/wx_accel.py", line 170, in collect_shortcuts
    collect_recurse(control, result, nameds, statics)
  File "src/wx_accel.py", line 151, in collect_recurse
    collect_recurse(children[i], result, nameds, statics)
  File "src/wx_accel.py", line 151, in collect_recurse
    collect_recurse(children[i], result, nameds, statics)
  File "src/wx_accel.py", line 153, in collect_recurse
    keys = parse_shortcuts(ctrl)
  File "src/wx_accel.py", line 120, in parse_shortcuts
    tool = ctrl.FindToolForPosition(i * ctrl.ToolSize[0], 0)
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_controls.py", line 3901, in FindToolForPosition
    return _controls_.ToolBarBase_FindToolForPosition(*args, **kwargs)
PyAssertionError: C++ assertion "Assert failure" failed at ./src/gtk/toolbar.cpp(700) in FindToolForPosition(): wxToolBar::FindToolForPosition() not implemented
Uncaught exception. Entering post mortem debugging
```

**Comment by suurjaak** [comment]
A new Skyperious version, 3.3, has just been released, where this error should be fixed. Can you confirm?

**Comment by neongreen** [comment]
Well, now another thing happens:

    (main.py:11151): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

    (main.py:11151): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
    Segmentation fault (core dumped)

**Comment by neongreen** [comment]
Ouch, forgot to say: it happens when I try loading a Skype database.

**Comment by neongreen** [comment]
Hm, and now I checked again... and it doesn't anymore. The `assertion 'height >= -1' failed` messages are still shown, but it loads as usual.

Guess this issue can be closed.

**Comment by suurjaak** [comment]
Thank you, closing the issue for now then.

**Comment by jkugler** [comment]
Odd. I'm getting this error with the master branch on Ubuntu 16.04. I had to install python-wxgtk3.0 and python-gobject.

Also, had to run this under a debugger, because all exceptions are swallowed by main.py:
```
if "__main__" == __name__:
    try: run()
    except KeyboardInterrupt: sys.exit()
```
Not sure why that doesn't raise other exceptions, but at any rate, I'm getting
```
File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 3901, in FindToolForPosition
  return _controls_.ToolBarBase_FindToolForPosition(*args, **kwargs)

wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/toolbar.cpp(702) in FindToolForPosition(): wxToolBar::FindToolForPosition() not implemented
```
in _controls.py line 3907.  Oddly, that's an error in the Python package. Same error when running the v3.5 branch.

Any ideas?

**Comment by jkugler** [comment]
Oh...that's weird. My debugger catches the exception, but it runs from the command line just fine. Must be a try/catch wrapping it somewhere else. Sorry for the noise.
